package com.application.tweetapp.tweet.document;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Reply")
public class Reply {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String replyId;
	@DynamoDBAttribute
	private String tweetId;
	@DynamoDBAttribute
	private String userLoginId;
	@DynamoDBAttribute
    private String comment;
	@DynamoDBAttribute
    private String repliedOn;
	public String getReplyId() {
		return replyId;
	}
	public void setReplyId(String replyId) {
		this.replyId = replyId;
	}
	public String getTweetId() {
		return tweetId;
	}
	public void setTweetId(String tweetId) {
		this.tweetId = tweetId;
	}
	public String getUserLoginId() {
		return userLoginId;
	}
	public void setUserLoginId(String userLoginId) {
		this.userLoginId = userLoginId;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public String getRepliedOn() {
		return repliedOn;
	}
	public void setRepliedOn(String repliedOn) {
		this.repliedOn = repliedOn;
	}
	public Reply(String replyId, String tweetId, String userLoginId, String comment, String repliedOn) {
		super();
		this.replyId = replyId;
		this.tweetId = tweetId;
		this.userLoginId = userLoginId;
		this.comment = comment;
		this.repliedOn = repliedOn;
	}
	public Reply() {
		super();
		// TODO Auto-generated constructor stub
	}
	@Override
	public String toString() {
		return "Reply [replyId=" + replyId + ", tweetId=" + tweetId + ", userLoginId=" + userLoginId + ", comment="
				+ comment + ", repliedOn=" + repliedOn + "]";
	}
	
	
	
	
    
	
}
