package com.application.tweetapp.tweet.document;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName ="Tweet")
public class Tweet {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
    private String tweetId;
	
	@DynamoDBAttribute
    private String userLoginId;
	@DynamoDBAttribute
    private String message;
	@DynamoDBAttribute
    private String postedOn;
	@DynamoDBAttribute
    private int likes;
	
	
	
	public Tweet() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Tweet(String tweetId, String userLoginId, String message, String postedOn, int likes) {
		super();
		this.tweetId = tweetId;
		this.userLoginId = userLoginId;
		this.message = message;
		this.postedOn = postedOn;
		this.likes = likes;
	}
	public String getTweetId() {
		return tweetId;
	}
	public void setTweetId(String tweetId) {
		this.tweetId = tweetId;
	}
	public String getUserLoginId() {
		return userLoginId;
	}
	public void setUserLoginId(String userLoginId) {
		this.userLoginId = userLoginId;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getPostedOn() {
		return postedOn;
	}
	public void setPostedOn(String postedOn) {
		this.postedOn = postedOn;
	}
	public int getLikes() {
		return likes;
	}
	public void setLikes(int likes) {
		this.likes = likes;
	}
	@Override
	public String toString() {
		return "Tweet [tweetId=" + tweetId + ", userLoginId=" + userLoginId + ", message=" + message + ", postedOn="
				+ postedOn + ", likes=" + likes + "]";
	}

    
}
