package com.application.tweetapp.tweet.document;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "User")
public class User {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String userId;
	
	@DynamoDBAttribute
    private String firstname;
    @DynamoDBAttribute
    private String lastname;
    @DynamoDBAttribute
    @Indexed(unique = true)
    private String email;

    @DynamoDBAttribute
    private String loginid;
    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private Long contact;
    @DynamoDBAttribute
    private boolean loggedIn;
    
	@Override
	public String toString() {
		return "User [userId=" + userId + ", firstname=" + firstname + ", lastname=" + lastname + ", email=" + email
				+ ", loginid=" + loginid + ", password=" + password + ", contact=" + contact + ", loggedIn=" + loggedIn
				+ "]";
	}

	public User(String userId, String firstname, String lastname, String email, String loginid, String password,
			Long contact, boolean loggedIn) {
		super();
		this.userId = userId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.loginid = loginid;
		this.password = password;
		this.contact = contact;
		this.loggedIn = loggedIn;
	}

	public User() {
		super();
		// TODO Auto-generated constructor stub
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLoginid() {
		return loginid;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Long getContact() {
		return contact;
	}

	public void setContact(Long contact) {
		this.contact = contact;
	}

	public boolean isLoggedIn() {
		return loggedIn;
	}

	public void setLoggedIn(boolean loggedIn) {
		this.loggedIn = loggedIn;
	}

	
   

}
